spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
  batch:
    job:
      enabled: false

#  sql:
#    init:
#      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql

server:
  port: 8099